import Navigation from "@/components/Navigation";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export default function FAQs() {
  const faqs = [
    {
      question: "What is AI Content Detector?",
      answer: "TruthGuard AI is an advanced platform that uses artificial intelligence to detect fake news, AI-generated text, and AI-generated images. Our system helps you verify the authenticity of digital content in real-time.",
    },
    {
      question: "How accurate are the results?",
      answer: "Our detection models achieve high accuracy rates, typically above 85-95% depending on the content type. However, no AI system is 100% accurate. We provide confidence scores with each analysis to help you make informed decisions.",
    },
    {
      question: "Will my data be saved?",
      answer: "No. We prioritize your privacy and security. All content you analyze is processed in real-time and immediately discarded after providing results. We do not store, log, or share any of your analyzed content.",
    },
    {
      question: "Is this service free?",
      answer: "Yes! TruthGuard AI is currently free to use for all registered users. Simply create an account to access all detection features including fake news detection, AI text detection, and AI image detection.",
    },
    {
      question: "How does the AI text detector work?",
      answer: "Our AI text detector analyzes linguistic patterns, sentence structure, vocabulary choices, and writing styles to determine whether text was written by a human or generated by AI. It works with various AI models including ChatGPT, GPT-4, Claude, and others.",
    },
    {
      question: "Can I detect AI-generated images?",
      answer: "Yes! Our AI image detection feature can identify AI-generated images including those created by popular tools like DALL-E, Midjourney, Stable Diffusion, and other generative AI models. Simply upload an image and our system will analyze it.",
    },
    {
      question: "What file formats are supported?",
      answer: "For text: We support direct paste, .txt, .doc, and .docx files. For images: PNG, JPG, JPEG, and WEBP formats are supported. Maximum file size is 10MB.",
    },
    {
      question: "When will video detection be available?",
      answer: "We're actively developing our deepfake video detection feature. Stay tuned for updates! You can check our Features page regularly for the latest announcements.",
    },
  ];

  return (
    <div className="min-h-screen bg-background">
      <Navigation />
      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <div className="text-center mb-12 space-y-4">
          <h1 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-primary via-accent to-primary bg-clip-text text-transparent">
            Frequently Asked Questions
          </h1>
          <p className="text-muted-foreground text-lg">
            Find answers to common questions about TruthGuard AI
          </p>
        </div>

        <Accordion type="single" collapsible className="w-full space-y-4">
          {faqs.map((faq, index) => (
            <AccordionItem
              key={index}
              value={`item-${index}`}
              className="border-2 border-border/50 rounded-lg px-6 hover:border-primary/50 transition-all duration-300 hover:shadow-lg hover:shadow-primary/10 animate-slide-up hover-lift"
              style={{ animationDelay: `${index * 0.1}s` }}
            >
              <AccordionTrigger className="text-left hover:text-primary transition-colors">
                {faq.question}
              </AccordionTrigger>
              <AccordionContent className="text-muted-foreground">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </div>
  );
}
